### 3.1

In [7]:
import numpy as np
import pandas as pd

# Representing Data in rows and 
data = {
    'Stuents': ['student 1', 'student 2', 'student 3', 'student 4'],
    'Math':    [80, 60 ,95 , 70],
    'English': [70, 85, 88, 60],
    'Science': [90, 75, 92, 65]}

DataR= pd.DataFrame(data)
DataR.head()






Stuents  Math  English  Science
0  student 1    80       70       90
1  student 2    60       85       75
2  student 3    95       88       92
3  student 4    70       60       65

### 3.2

In [14]:
# representing data in array

student1= np.array([80,70, 90])
student2= np.array([60,85, 75])
student3= np.array([95,88, 92])
student4= np.array([70,60, 65])

student1
student2
student3
student4
# total
print("Total for student1:", np.sum(student1))
print("Total for student2:", np.sum(student2))
print("Total for student3:", np.sum(student3))
print("Total for student4:", np.sum(student4))




Total for student1: 240
Total for student2: 220
Total for student3: 275
Total for student4: 195


### 3.3

In [30]:
# Applying scaler multiplication, Making mathematics Twice important
# putting all in a column

students= np.array([[80,70, 90],
                    [60, 85, 75],
                    [95, 88, 92],
                    [70, 60, 65]
                    ])

print(students)
scaler_c= 2
# Making math twice important is scaler multiplication of maath column
# scaler_multi= np.dot(scaler_c, axis=1)

students_twice_math = students.copy()
students_twice_math[:, 0] = scaler_c * students_twice_math[:, 0]
print(students_twice_math)
Total= students_twice_math[:, 0].sum()
scale_x=students_twice_math[:, 0]
print("scaler Result:",scale_x)
print("scaler multiplication of math Total:", Total)


[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
scaler Result: [160 120 190 140]
scaler multiplication of math Total: 610


### 3.4

In [ ]:
students= np.array([[80,70, 90],
                    [60, 85, 75],
                    [95, 88, 92],
                    [70, 60, 65]
                    ])
Average_math= students[:,0].sum()/ 4
Average_eng= students[:, 1].sum()/ 4
Average_sci= students[:, 2].sum()/ 4

print(f"Average mathematics: {Average_math}")
print(f"Average English: {Average_eng}")
print(f"Average sci: {Average_sci}")

Average mathematics: 76.25
Average English: 75.75
Average sci: 80.5


### 3.5

In [41]:
weight_vector= np.array([[0.5], [0.3], [0.2]])

final_grade= np.dot(students, weight_vector)
print(final_grade)

[[79. ]
 [70.5]
 [92.3]
 [66. ]]


### 3.6

In [47]:
# comparing scores of student1 3

Average_student1= students[2,:].sum()- students[0,:].sum()
print("difference in score vector:", Average_student1)

difference in score vector: 35
